scripts/start-tunnel

A little extra feedback while (re)connecting:
* **PR #1** 👈

Show tunnel status in terminal title

---

schema.sql
src/app/api/backup-configs/[id]/backups/route.ts
src/app/api/backup-configs/route.ts
src/app/configs/[id]/createBackup.ts
src/app/configs/[id]/page.stories.tsx
src/app/configs/[id]/page.tsx
src/app/swr.tsx
src/app/types.tsx

* **PR #17** 👈
* **PR #16**
* **PR #11**

feat: can "create" a backup (but it doesn't do anything)

---

scripts/migrations/00001_initial/index.sql
src/app/api/backup-configs/[id]/blobs/route.ts
src/app/configs/[id]/createBackup.ts
src/app/configs/[id]/page.stories.tsx
src/app/configs/[id]/page.tsx
src/app/swr.tsx
src/app/types.tsx
src/lib/server/db.ts

Blobs need to be tracked separately, and associated with both a backup and a "backup config"
Add the database schemas and backup function logic to back up and track blobs.

feat: add blob backup

---

src/app/Sidebar.stories.tsx
src/app/configs/Form.tsx
src/app/configs/[id]/createBackup.ts
src/app/configs/[id]/page.stories.tsx
src/app/configs/[id]/page.tsx
src/app/configs/new/action.ts
src/app/types.tsx
src/lib/server/db.ts

postgres.js has support for default transforms: enable two of them:
1. translate `undefined` to `null` automatically - useful for inserts and for allowing us to use normal "optional field" syntax in Typescript defs 
2. translate snake_case to camelCase and vice-versa when coming out of and going in to the database

feat: use camelCase in JavaScript

---

components.md
package.json
pnpm-lock.yaml
scripts/migrations/00001_initial/index.sql
src/app/api/snapshots/[id]/route.ts
src/app/backups/Form.tsx
src/app/backups/[id]/CreateSnapshotButton.tsx
src/app/backups/[id]/createSnapshot.ts
src/app/backups/[id]/page.stories.tsx
src/app/layout.tsx
src/app/swr.tsx
src/app/types.tsx
src/components/Backup.tsx
src/components/Backup/Backup.tsx
src/components/Backup/Restore.tsx
src/components/Backup/index.tsx
src/components/Dashboard.tsx
src/components/Restore.tsx
src/components/RestoreUI.tsx
src/components/ui/Button.tsx
src/hooks/use-plan.ts
src/lib/server/db.ts
src/store/ui.ts

This is extremely rough, but if someone wants to tackle the rest of the styling please feel free to merge!

feat: add snapshot detail modal

---

scripts/start-tunnel

fix: Tunnel script correctly adds tunnel to env

---

deploy/shared/main.tf
deploy/shared/variables.tf

We're not on cloudflare as it turns out :) but I'm still requiring the zone id.

fix(deploy): fix unused variable for cloudflare

---

src/components/Backup/index.tsx
src/hooks/use-disclosure.ts

CI still not running build in PRs, will fix right now

fix: two fixes for a broken build

---

.github/workflows/deploy.yml

Fixes the workflow triggers on the deploy task

ci(github): fix workflow triggers

---

.github/workflows/deploy.yml

Try #2 at fixing event triggers

ci(github): fix deploy event triggers, try 2

---

.github/workflows/deploy.yml

Giving up on workflow_run, test is run seperately than deploy

ci(github): fix deploy action, remove test flow

---

.github/workflows/deploy.yml

Fix release-please, which apparently now needs the issues: write permission

ci(github): add missing permission on release step

---

.github/workflows/terraform.yml
Makefile

Insure cross platform compatibility for developers deploying x86 systems

ci(github): use buildx

---

src/components/BackupScreen/BlueskyAccountSelect.tsx

fix: revert bluesky account selector for now

---

src/lib/server/db.ts

without this my authz checks weren't working properly

fix: add account_did to backup queries

---

.env.tpl
.github/actions/env-setup/action.yml
.github/actions/pnpm/action.yml
.github/workflows/chromatic.yml
.github/workflows/test.yml
package.json
pnpm-lock.yaml

chore: Get Chromatic going

---

src/app/atproto/oauth/route.ts
src/components/BackupScreen/BlueskyAccountSelect.tsx
src/lib/sessions.ts

also some minor tweaks to the bluesky account selector to go back to a popup window and display

fix: don't set session in route

---

knip.jsonc
src/app/LoggedIn.tsx
src/app/swr.tsx

make sure all API fetchers return `error`s on HTTP error - this fixes session init

fix: session initialization

---

src/components/BackupScreen/BackupDetail.tsx
src/components/ui/modal.tsx

this prevents form submissions when modal buttons are clicked
also remove unused modal

fix: move modal to a portal

---

src/components/modals/create-space.tsx
src/lib/constants.ts

1) use the storacha client from `useAuthenticator` 
2) specify a gateway for authorization manually like we do in console

fix: space creation fixes

---

.storybook/decorators/withAuthContext.tsx
src/app/Sidebar.tsx
src/app/authentication.tsx
src/app/page.stories.tsx
src/app/page.tsx
src/components/Loader.stories.tsx
src/components/Loader.tsx

feat: Loaders work

---

src/app/atproto/connect/page.tsx
src/app/backups/[id]/CreateSnapshotButton.tsx
src/app/global.css
src/app/layout.tsx
src/app/snapshots/[id]/SnapshotPage.tsx
src/app/snapshots/[id]/repo/RepoPage.tsx
src/app/snapshots/[id]/restore/RestorePage.tsx
src/app/snapshots/layout.tsx
src/components/BackupScreen/BackupDetail.tsx
src/components/Restore.stories.ts
src/components/Restore.tsx
src/components/RestoreUI.tsx
src/components/SnapshotScreen/SnapshotDetail.tsx
src/components/SnapshotScreen/SnapshotScreen.tsx
src/components/ui/Button.tsx
src/components/ui/input.tsx
src/lib/server/backups.ts

plus polish in a few other places

feat: lots of cleanup in the restore flow

---

src/components/BackupScreen/BackupDetail.tsx
src/components/BackupScreen/StorachaSpaceSelect.tsx
src/components/ui/CreateButton.tsx

feat: Improve layout of `BackupDetail`

---

deploy/app/main.tf
deploy/shared/main.tf

Allow next js to write to the cache in the container
Turn off readonlyFileSystem for the container

fix(deploy): allow writes to the file system in the container

---

deploy/app/cron.tf

Add a dead letter queue for the backup cron to see what's failing

fix(cron): add dead letter queue

---

package.json
pnpm-lock.yaml
src/lib/server/db.ts

eg, `/backups/new`, which now tries to look up the Backup with id `new`… 😅
* **PR #100** 👈

fix: Don't blow up on bad UUIDs

---

scripts/migrate.mjs

This one's absurdly simple, but it makes other PRs simpler to pull it out.
* **PR #98** 👈

refactor: Format migration script

---

.github/workflows/test.yml
package.json

chore: Add `check-all` script to make refactoring easier

---

src/app/snapshots/[id]/blobs/BlobsPage.tsx

chore: Fix `no-useless-rename`

---

README.md

make this a fix to trigger a release

fix: tweak readme

---

package.json
pnpm-lock.yaml
src/app/Sidebar.tsx
src/components/BackupScreen/DataBox.stories.tsx
src/components/BackupScreen/DataBox.tsx
src/lib/delegate.tsx
src/lib/server/backups.ts
src/lib/ui.ts

Brings in https://github.com/storacha/upload-service/pull/250 to fix the Create Backup button pending state. Also removes the last vestige of `@w3ui/react`, because why not.
Fixes https://github.com/storacha/project-tracking/issues/418
* **PR #115** 👈
* **PR #116**

fix: Create Backup button should show pending state

---

package.json
pnpm-lock.yaml
src/lib/server/backups.ts
src/lib/storacha.ts

chore: Avoid `@storacha/ui-react` on server-side code

---

package.json
pnpm-lock.yaml
scripts/migrations/00002_refresh_locks/index.sql
src/app/atproto/oauth-client-metadata/[account]/route.ts
src/lib/atproto.ts
src/lib/server/db.ts

build a simple locking mechanism on top of a posgres table
if this isn't enough or is buggy we should consider using redlock and the implementation on the README here: https://www.npmjs.com/package/@atproto/oauth-client-node

feat: simple request lock for bluesky oauth

---

package.json
pnpm-lock.yaml
scripts/migrations/00002_refresh_locks/index.sql
scripts/migrations/00003_at_blobs/index.sql
src/lib/atproto.ts
src/lib/server/backups.ts
src/lib/server/db.ts
src/types.tsx

using cid as the database id was a bad idea - I want to be able to track the same cid on different backups and snapshots and this was preventing that, and breaking snapshots
introduce a new table and don't drop the old one - we can do that manually

fix: rework the blob database model

---

.github/workflows/terraform.yml

need to add the new secret to terraform

fix: production deploy issue

---

.github/workflows/chromatic.yml

chore: Chromatic: `autoAcceptChanges` on `main`

---

src/app/authentication.tsx
src/app/session/destroy/route.tsx

this was leading to some very weird stuff

fix: destroy session on logout

---

src/components/BackupScreen/Select.stories.tsx
src/components/BackupScreen/Select.tsx

fix: Select values truncate rather than wrap

---

src/components/BackupScreen/BlueskyAccountSelect.tsx
src/components/BackupScreen/Select.stories.tsx

fix: Actually set the name on the `Select` 🤦‍♀️

---

src/components/modals/create-space.tsx

DOH - spaces won't work unless they're provisioned

fix: provision spaces on creation

---

src/app/AppLayout.tsx
src/app/LoggedIn.tsx
src/app/page.tsx
src/app/snapshots/[id]/restore/RestorePage.tsx
src/components/Loader.tsx
src/components/RestoreUI/RestoreUI.tsx
src/components/RestoreUI/dynamic.tsx
src/components/ui/spinner.tsx

fix: Spinner for buttons, Loader for pages

---

src/app/atproto/connect/page.tsx

https://github.com/user-attachments/assets/bc251fff-233c-449a-ad6b-cb53e20310de
- added auto append to handles ([#436](https://github.com/storacha/project-tracking/issues/436))

fix: auto appends .bsky.social to user handles

---

scripts/migrations/00005_must_back_up_something/index.sql
src/components/BackupScreen/BackupDetail.tsx
src/components/BackupScreen/DataBox.tsx

Fixes https://github.com/storacha/project-tracking/issues/421
* **PR #154**
* **PR #157** 👈

fix: Shouldn't be able to back up nothing

---

src/app/LoggedIn.tsx
src/app/backups/[id]/BackupPage.tsx
src/app/backups/[id]/snapshots/SnapshotPage.tsx
src/app/backups/[id]/snapshots/page.tsx
src/components/ui/CreateButton.tsx
src/components/ui/KeychainView.tsx
src/lib/server/db.ts

don't show buttons that require the private key unless it's loaded
plus, add a barebones snapshot page

fix: two small tweaks to the identity manager

---

src/components/BackupScreen/Select.tsx

Closes https://github.com/storacha/project-tracking/issues/422
* **PR #166** 👈

feat: Accounts are required to create a backup

---

.storybook/modes.ts
src/app/page.stories.tsx
src/components/LoginScreen/index.tsx

Via Chromatic:
Fixes https://github.com/storacha/project-tracking/issues/447
* **PR #167** 👈

fix: Match footer to storacha.network

---

src/components/ui/KeychainView.stories.tsx

Otherwise, the snapshots change every time.
* **PR #169** 👈

chore: Story (and Chromatic) uses constant data

---

src/app/api/backups/[id]/snapshots/route.ts

it was assuming 0, 0 for these, which is nonsensicle

fix: set defaults for snapshots URL

---

src/app/api/backups/[id]/blobs/route.ts
src/app/backups/[id]/BackupPage.tsx
src/components/BackupScreen/BackupDetail.tsx
src/components/Blobs.tsx

- pass pagination along to backups blobs
- move blobs link into the sidebar
- move loader to the top of the page

fix: a few bits of cleanup in the blobs page

---

src/app/global.css
src/components/BackupScreen/Switch.tsx

- Added new colour for disable switch.
Closes [#446](https://github.com/storacha/project-tracking/issues/446)

fix: add disable switch color

---

src/components/modals/create-space.tsx

feel very dumb not to have caught this in review, but of course we should be using the `client` instance from the authenticator - otherwise it won't talk to the right service
also add error handling so we don't just ignore failures here!

fix: use client from authenticator in space creator

---

src/app/page.stories.tsx

chore: Bring back logged in story (now with plan)

---

.storybook/main.ts
src/app/api/keys/[id]/route.ts
src/components/ui/KeyImportForm.tsx
src/components/ui/KeyMaterialImportForm.tsx
src/components/ui/KeychainView.stories.tsx
src/components/ui/KeychainView.tsx
src/contexts/keychain.tsx
src/lib/server/auth.ts
src/lib/server/db.ts

- fix a number of UX bugs
- implement "forget key"
- implement "import key"
https://github.com/user-attachments/assets/d8af6c93-a447-4bb4-ab8d-6147ae8816dc

feat: recovery key flow polish

---

deploy/.env.production.local.tpl

NEXT_PUBLIC_HUMANODE_OAUTH_CALLBACK_URL isn't showing up in staging for some reason, try to fix that

fix: add empty line to .env.production.local.tpl

---

deploy/.env.production.local.tpl

This reverts commit 04865fbfc9bdcb0ccb6542f7d8654a5930e97e39.

fix: Revert "fix: point bsky.storage at the new DID (#222)"

---

src/components/RestoreUI/RestoreDialogView.stories.ts
src/components/RestoreUI/RestoreDialogView.tsx
src/components/RestoreUI/RestoreUI.tsx
src/components/SnapshotScreen/SnapshotScreen.tsx
src/types.ts

1) make sure we read ALL blobs, not just the first page 
2) give users the option to restore just the images from one snapshot OR all images that we've ever saved as part of this "backup" 
3) remove the feature flag!

feat: get restore flow working
