storacha/bluesky-backup-webapp-server

README.md, package.json, pnpm-lock.yaml, src/components/Backup/Backup.tsx, src/components/Switch/index.tsx, src/components/ui/Button.tsx
My internet has been quite poor lately. Uploading a demo takes forever compared to uploading a screenshot. 
Here's a focus state enabled when i tab + space to simulate a "on/off" state with the switch.
=> feat(ui): use react-aria packages to make the Switch component accessible/controllable via keyboard

src/app/backups/[id]/CreateSnapshotButton.tsx, src/app/swr.tsx, src/components/Backup/Backup.tsx, src/components/Backup/Restore.tsx, src/components/ui/CreateButton.tsx
Solves three problems, one commit at a time:
* The styling for the buttons was duplicated; now it's all in one place. I've named the common styling `CreateButton`, but noted that we probably don't know what that style of button actually signifies yet, and the name should evolve.
* A function performing the SWR mutation was being passed into the component, but a server component can't pass a function to a client component, because it can't be serialized. That's okay, though, because the button should really know enough to do the mutation itself, since it also does the actual request. I've done it in a slightly fancy way by using `useSWRMutation`, but it means we get some type safety on the key, just like with `useSWR`.
* The wrong key was being mutated: we want the list of Snapshots, not …
=> fix: Solve a few issues with the Create Snapshot button

.github/workflows/test.yml, src/components/Backup/index.tsx
we'll probably want to refactor to make this a bit more precise later, but this isn't bad and fixes the build
I considered adding build to the test step so we don't miss this in the future, but it's a little bit of work and I want to unbreak the build
=> fix: put BackupDetail behind Suspense for now

.github/workflows/test.yml
this means we may run the build more than once when deploying in docker, but I think that's actually useful information - the regular build may success and the docker build may fail and that's useful
=> fix: add pnpm build to CI

.github/workflows/terraform.yml, Makefile
Github runs on x86 runners by default but we need docker compiled for ARM
=> build(Makefile): make sure docker is built for the correct architecture

src/components/Dialog.tsx
As it was, `onClose` was invalid, because it wasn't serializable. `"use client"` marks a client entry module, meaning a point in the tree where a server component renders a client component. A server component can't render this client component, because it can't pass it an `onClose` value. But that's okay, it wouldn't make much sense anyway.
* **PR #67** 👈
=> fix: Remove "use client" from Dialog component

scripts/migrations/00001_initial/index.sql, scripts/migrations/00002_add_delegation_to_backup/index.sql, src/app/Sidebar.stories.tsx, src/app/Sidebar.tsx, src/app/api/backups/[id]/blobs/route.ts, src/app/api/backups/[id]/snapshots/route.ts, src/app/api/snapshots/[id]/route.ts, src/app/backups/[id]/BackupPage.tsx, src/app/backups/[id]/createSnapshot.ts, src/app/backups/[id]/page.stories.tsx, src/app/backups/[id]/page.tsx, src/app/backups/new/page.stories.tsx, src/app/types.tsx, src/components/BackupScreen/BackupDetail.tsx, src/components/BackupScreen/Restore.tsx, src/components/Restore.tsx, src/components/RestoreUI.tsx, src/lib/server/auth.ts, src/lib/server/backups.ts, src/lib/server/db.ts
I floated this in chat and got a good response:
```I'm thinking it would be better to use a UUID. numbers leak information about how many backups we've done in general, and imho kind of look silly because they show up in URLs and won't have any real discernable pattern.
```
=> chore: change type of ids from numbers to uuids

knip.jsonc
=> chore: Stop ignoring `@vercel/ncc`; it's uninstalled now

deploy/app/cron.tf
the authorization for the cron is failing cause it's not authorized, because the policy is not attached to the role
=> fix(deploy/app): attach role to policy

scripts/migrations/00003_at_blobs/index.sql, src/lib/server/backups.ts, src/lib/server/db.ts, src/types.tsx
using cid as the database id was a bad idea - I want to be able to track the same cid on different backups and snapshots and this was preventing that, and breaking snapshots
introduce a new table and don't drop the old one - we can do that manually
I merged https://github.com/storacha/bluesky-backup-webapp-server/pull/114 wrong, this fixes that
=> fix: rework the blobs datamodel

scripts/migrate.mjs
the URL generated in the docker container has no `file://` on it, so account for that
=> fix: migration script

src/app/LoggedIn.tsx
The previous copy was more like a log message. The user doesn't need to be told they were (or are being) redirected, and "successfully" should be assumed.
* **PR #149** 👈
* **PR #150**
=> feat: Toast copy is more user-oriented

README.md, src/app/snapshots/[id]/blobs/BlobsPage.tsx, src/app/snapshots/[id]/repo/RepoPage.tsx, src/components/BackButton.tsx, src/components/ui/Button.tsx
Initially, `<BackButton />` only renders on mobile and uses router.back(), which pretty much relies on the history API.
Now, it accepts an optional path prop if you want to be explicit about where to 'go back' to.
---
fixes [#434](https://github.com/storacha/project-tracking/issues/434)
=> fix: render 'back button' on large screens if the path is specified

src/components/ui/KeyImportForm.tsx
Without this, 1Password will prompt to save the `keyMaterial` field as a password. 1Password is a great place to store the key material, but it doesn't function like a password, so the automatic system doesn't really work for us, and this in particular is not where the value is *created* but where it's *used*.
The `data-1p-ignore` attribute is not documented, but it does appear to work.
* **PR #162** 👈
=> fix: Tell 1Password to ignore `keyMaterial`

src/components/CopyButton.tsx
Change the hover text (`title`) when clicked. Keep the *label* (`aria-label`), which is still correct once the button is clicked.
* **PR #163** 👈
=> feat: Add hover text to `CopyButton`

src/app/atproto/connect/page.tsx, src/app/identities/[id]/IdentityPage.tsx, src/components/ui/IdentityTransferView.tsx, src/components/ui/KeychainView.tsx, src/components/ui/text.tsx
All functionally refactoring. Not sure why the bad CSS syntax wasn't more of a problem, but it's gone now.
The "big" change is to `SubHeading`, making it not capitalized by default. Turns out it's desired less often than not. Generally, sub-headings probably shouldn't be capitalized anyway. They tend to be sentences, not nouns.
* **PR #165** 👈
=> refactor: Fix up some CSS

src/app/api/backups/[id]/snapshots/route.ts, src/app/backups/[id]/BackupPage.tsx, src/app/backups/[id]/page.stories.tsx, src/app/backups/[id]/snapshots/SnapshotPage.tsx, src/components/BackButton.tsx, src/components/Pagination.stories.tsx, src/components/Pagination.tsx, src/components/ui/Button.tsx, src/components/ui/Stack.tsx, src/components/ui/style.ts, src/lib/constants.ts, src/lib/server/db.ts, src/lib/swr.tsx, src/types.tsx
I've updated the `findSnaphots` method in the storage context to return paged results and updated the API routes to access this data with query parameters
In the snapshot component, there's a tiny UX hack where I'm rendering the Snapshots in a div that is hidden. This ensures that the SWR cache is always updated with fresh data for the next page, allowing navigation to be instant.
addresses [#448](https://github.com/storacha/project-tracking/issues/448)
=> feat: list all snapshots

src/app/atproto/connect/connectHandle.ts, src/app/atproto/connect/error.tsx, src/app/atproto/connect/page.tsx, src/app/atproto/connect/ui.tsx
1) use a server action to enable us to show progress (I tried a few other ways to no avail) 
2) move handle inference to the server action - the quick little handle update didn't look great and the user sees the full handle on the next screen
3) add error handling - we were just throwing an error if a user, for instance, entered a nonexistent handle. now we show the error and let them reset the form, per the [next.js docs](https://nextjs.org/docs/app/api-reference/file-conventions/error)
=> fix: polish up the bluesky account connection flow

next.config.ts, src/components/services.ts
This allows us to distinguish invocations made by this app vs others. Allows us to track the relative success of this application.
You may want to set `NEXT_PUBLIC_VERSION` environment var or load from `package.json` at some point...
=> feat: add x-client header

src/components/BackupScreen/BackupDetail.tsx, src/components/SharedScreen.tsx
we should ideally only be able to resize the panels on large viewports, not on mobile. from the previous iteration, sometimes, the 'backup & restore' pane covers the content of 'backup detail', which isn't desirable.
closes [#460](https://github.com/storacha/project-tracking/issues/460)
=> fix(ui): remove resizable panels on mobile

src/components/ui/Button.tsx, src/components/ui/KeychainView.tsx
this lets users record their secret keys without showing them on the screen
=> feat: add a "copy secret" button to the new key dialog

src/app/api/snapshots/[id]/blobs/route.ts
people who have many blobs are not able to see the next set of data (blobs) when they click on the pagination component to view the next page.
**what caused this?**
the optional parameters were missing in the `findBlobsForSnapshot` db accessor
=> fix: pagination issue in the blobs explorer

src/app/BackupExplainer.tsx, src/app/LoggedIn.tsx, src/app/Sidebar.tsx, src/app/backups/[id]/RightSidebarContent.tsx, src/app/backups/[id]/snapshots/SnapshotPage.tsx, src/components/BackupScreen/BackupDetail.tsx, src/components/Blobs.tsx, src/components/CopyButton.tsx, src/components/RestoreUI/RestoreDialogView.tsx, src/components/SnapshotScreen/SnapshotDetail.tsx, src/components/ui/text.tsx
Respond to feedback in #205 thanks @alanshaw! I think I got to most of your feedback - much of it was obviated by earlier changes, and a couple things are slightly bigger projects, but I think this is good stuff all around:
* move "backup explainer" to a more sensible place (the "empty backups list" space on desktop and above the backup creation form if no backups on mobile)
* don't show "add backup" in the left sidebar if we're on the backup creation page
* clean up snapshot list items in the sidebar and on the snapshots page
* sprinkle on some more copy buttons next to shortened strings
* default backup name to "My Bluesky Backup"
* rename "blobs" "media" in a bunch of places in the UI
=> fix: assorted changes from feedback from @alanshaw

deploy/app/main.tf, deploy/shared/main.tf
Fix staging deploys
Bluesky and telegram were over writing each other unfortunately for the staging replication, which turns out to be a singleton-per-region object. so it's configured manually for now.
update storoku, which leaves replication to be configed manually
=> fix(deploy): remove staging replication

deploy/.env.production.local.tpl
pointing at the old one doesn't work with the new backend
we need to keep NEXT_PUBLIC_STORACHA_PROVIDER pointing at the same DID for now to ensure space creation works
=> fix: point bsky.storage at the new DID

src/contexts/keychain.tsx
fixes `/api/key` being fetched before an account has been authenticated.
context: https://bsky.app/profile/trav.page/post/3lrl36uftlc2i
docs: https://swr.vercel.app/docs/conditional-fetching
=> fix: dont fetch `/api/keys` without auth
